---
- name: DEPLOY AS3 DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    uri_method: POST

  vars_files:
    - ../creds/big_creds.yaml

  tasks:

    - name: REST CALL TO BIG-IP
      uri:
        url: https://3.9.51.94/mgmt/shared/appsvcs/declare
        method: "{{ uri_method }}"
        user: "{{ bigip_user }}"
        password: "{{ bigip_pass }}"
        body: "{{ lookup('file','./as3-declaration.json') }}"
        force_basic_auth: yes
        body_format: json
        status_code: 200
        validate_certs: no
      register: as3_output

    - name: DEBUG AS3 OUTPUT
      debug:
        msg: "MY AS3 OUTPUT {{ as3_output }}"
...